server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/store?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:store_user}
    password: ${DB_PASSWORD:store_pass}


  jpa:
    hibernate:
      ddl-auto: none          # Flyway owns the schema
    properties:
      hibernate.format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs.path: /v3/api-docs
  swagger-ui.path: /swagger

app:
  jwt:
    secret: "911b439f20503c99ef81a492acc36dad6893269198115c76ffd7984014ac8668" # dev only
    expiration: 3600000   # 1 hour in ms
